const taskData = [
    { n: "Peaceful Obstacle", d: "• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Recycling Station Hut</span> bölgesinde etkileşime gir.\n• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Motel Military Tent</span> bölgesinde etkileşime gir." },
    { n: "Undercurrent", d: "• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Stable</span>, <span class='hl'>Recycling Station</span> veya <span class='hl'>Motel</span> bölgelerinde toplam <span class='hl'>6 düşman</span> öldür.\n• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Artificial Lake Hut</span> bölgesinde bulunan <span class='hl'>1 adet yağmalanmamış bilgisayarı</span> yağmala." },
    { n: "The Long Game", d: "• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Wheatfield Farmhouse</span> yatak odası duvarıyla etkileşime gir.\n• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Cemetery Hut</span> yatak odası duvarıyla etkileşime gir.\n• <span class='hl'>Farm</span> haritasındaki bir raidden <span class='hl'>başarıyla çıkış</span> yap." },
    { n: "Frontline Reconnaissance", d: "• Marketten <span class='hl'>Mountain Spring Water</span> ve <span class='hl'>Biscuit</span> satın al.\n• <span class='hl'>Valley</span> haritasına bu öğelerle gir ve <span class='hl'>Abandoned Shack</span> bölgesine yerleştir." },
    { n: "Letter From Abyss", d: "• Marketten <span class='hl'>Signal Jammer</span> satın al ve <span class='hl'>Northridge</span> haritasına gir.\n• <span class='hl'>Lakeside Helicopter Point</span> içinde <span class='hl'>45 saniye</span> bekle.\n• Yakındaki <span class='hl'>Access Bridge</span> köprüsünde etkileşime gir." },
    { n: "Tooth For A Tooth", d: "• <span class='hl'>Valley</span> haritasında <span class='hl'>4 adet Urgent Mission</span> (ünlem simgesi) tamamla." },
    { n: "Viper's Tongue", d: "• <span class='hl'>Northridge</span> haritasındaki <span class='hl'>Cable Car</span>, <span class='hl'>Parking Lot</span> veya <span class='hl'>Hotel</span> bölgelerinde toplam <span class='hl'>6 düşman</span> öldür." },
    { n: "Protection And Responsibility", d: "• <span class='hl'>Farm</span> haritasının doğu tarafında <span class='hl'>3 oyuncu</span> öldür.\n• <span class='hl'>Farm</span> haritasındaki <span class='hl'>Villa</span> bölgesinde etkileşime gir." },
    { n: "Support The Flank", d: "• <span class='hl'>Farm</span> haritasının batı bölgesinde <span class='hl'>3 oyuncu</span> öldür.\n• <span class='hl'>Farm</span> haritasından <span class='hl'>1 kere başarıyla çıkış</span> yap." },
    { n: "The Bait", d: "• Toplam <span class='hl'>20 adet Miscellaneous Paper Items</span> bağışla.\n• <span class='hl'>Farm</span> haritasındaki <span class='hl'>The House</span> yerleşkesinin 2. katında etkileşime gir." },
    { n: "Risk Assessment", d: "• <span class='hl'>Northridge</span> haritasında <span class='hl'>susturuculu Marksman Rifle</span> ile <span class='hl'>6 düşman</span> öldür." },
    { n: "Special Operation", d: "• <span class='hl'>Valley</span> haritasında <span class='hl'>3 oyuncu</span> öldür." },
    { n: "Black Box", d: "• <span class='hl'>Farm</span> haritasında <span class='hl'>4 adet Urgent Mission</span> görevi yap." },
    { n: "Damage Control", d: "• <span class='hl'>Farm</span>'da <span class='hl'>2 adet yağmalanmamış Encrypted Safe</span> yağmala.\n• Tek maçta <span class='hl'>350k değerinde ganimetle</span> çıkış yap." },
    { n: "Good Intentions", d: "• <span class='hl'>Armory</span> haritasının dış bölgesinde <span class='hl'>6 düşman</span> öldür." },
    { n: "Synergy", d: "• <span class='hl'>Valley</span> haritasında <span class='hl'>Small Factory</span>, <span class='hl'>Noan Courtyard</span> veya <span class='hl'>Supply Camp</span> bölgelerinde <span class='hl'>6 düşman</span> öldür." },
    { n: "No Defiance", d: "• <span class='hl'>Valley</span> haritasında <span class='hl'>Noan Courtyard</span> ve <span class='hl'>Small Factory</span> bölgelerinde puan topla." },
    { n: "Respect", d: "• Toplam <span class='hl'>20 adet Miscellaneous Computer Parts</span> bağışla.\n• <span class='hl'>Armory Intelligence Center</span> bölgesinde etkileşime geç." },
    { n: "Burning Bridges", d: "• <span class='hl'>Valley</span> haritasında herhangi bir zorlukta <span class='hl'>1 maç tamamla</span>." },
    { n: "Frog In A Well", d: "• Marketten <span class='hl'>1 milyon nakit</span> çek.\n• <span class='hl'>Valley RV Camp</span> bölgesinde <span class='hl'>3 adet unsearched suitcase</span> yağmala." },
    { n: "Surprise Discovery", d: "• <span class='hl'>Valley Abandoned Shack</span> noklardan çıkış yap.\n• Workbench'te <span class='hl'>5.7x28mm L191</span> mermisi üret." },
    { n: "Rally", d: "• <span class='hl'>Portable Transceiver</span> ile <span class='hl'>Valley Port</span> bölgesinde <span class='hl'>60 saniye</span> bekle.\n• Aynı bölgede <span class='hl'>6 düşman</span> öldür." },
    { n: "Abondoned Airport", d: "• <span class='hl'>TV Station Parking Lot</span> puan topla.\n• <span class='hl'>TV Station</span> haritasında <span class='hl'>7 tane unsearched iş çantası</span> yağmala." },
    { n: "Signal", d: "• <span class='hl'>TV Station</span> haritasında <span class='hl'>AMB-17, T191 veya U191</span> ile <span class='hl'>3 oyuncu</span> öldür." },
    { n: "Bad Omen", d: "• <span class='hl'>Farm Stable Hut</span> etkileşime gir.\n• <span class='hl'>Farm Motel</span> bölgesinde puan topla." },
    { n: "Secret Southwest Passage", d: "• <span class='hl'>Rangefinder Binoculars</span> ile <span class='hl'>Airport Ticket Hall</span> etkileşim.\n• <span class='hl'>Airport</span> haritasında <span class='hl'>3 adet araba bagajı</span> aç." },
    { n: "Building A Stronghold", d: "• <span class='hl'>Airport Fuel Storage</span> veya <span class='hl'>Construction</span> bölgelerinde <span class='hl'>10 düşman</span> öldür.\n• <span class='hl'>Airport</span> haritasında <span class='hl'>3 adet Encrypted Safe</span> yağmala." },
    { n: "Investigation", d: "• <span class='hl'>KSS2 Kask + Spartan B Zırh + M4A1</span> ile <span class='hl'>8 tane White Wolves</span> öldür." },
    { n: "Lockdown", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>10 tane unsearched Biscuit Tin</span> yağmala." },
    { n: "Close Encounters", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>4 adet unsearched Small Safe</span> yağmala." },
    { n: "Ambushed", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>3 adet Urgent Mission</span> görevi yap." },
    { n: "Decoy", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>Exhibition Area</span>, <span class='hl'>Parking Lot</span> ve <span class='hl'>Control Tower</span> etkileşimlerini yap." },
    { n: "Old Rival", d: "• <span class='hl'>T-171 Cihazı</span> ile <span class='hl'>Airport Military Post</span> etkileşime gir.\n• En az <span class='hl'>2 adet ana silah</span> ile çıkış yap." },
    { n: "Pincer Movement", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>15 adet yiyecek/içecek</span> topla.\n• Kutuda toplam <span class='hl'>750k değerinde eşya</span> zulala." },
    { n: "The Trap", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>6 adet unsearched dumpster</span> yağmala." },
    { n: "Frontline Interception", d: "• <span class='hl'>Permission Card</span> ile <span class='hl'>Airport Military Zone</span> etkileşime gir." },
    { n: "Reckless Advance", d: "• <span class='hl'>Airport Dış Bölge</span> kısmında <span class='hl'>3 oyuncu</span> öldür." },
    { n: "Race Against Time", d: "• <span class='hl'>Airport</span> haritasından <span class='hl'>7 adet Energy Item</span> ile çıkış yap.\n• <span class='hl'>3 adet mor+ Energy Item</span> bağışla." },
    { n: "Emergency Measures", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>15 adet medikal eşya</span> çıkar." },
    { n: "Upwind", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>el bombasıyla 6 düşman</span> öldür.\n• <span class='hl'>Helicopter Extraction</span> noktasından çıkış yap." },
    { n: "Breakout", d: "• <span class='hl'>Airport Control Area</span>'da <span class='hl'>1 oyuncu</span> öldür.\n• <span class='hl'>Central Elevator</span> asansöründen çıkış yap." },
    { n: "Next Battlefield", d: "• Toplamda <span class='hl'>3 milyon ganimet</span> ile çıkış yap.\n• <span class='hl'>3 adet Altın (Sarı) eşya</span> bağışla." },
    { n: "Mission Failed", d: "• <span class='hl'>TV Station</span> haritasından <span class='hl'>15 adet mor+ eşya</span> çıkar.\n• <span class='hl'>Main Entrance</span> çıkış yap." },
    { n: "Edelweiss's Past", d: "• <span class='hl'>AKM + SH18 + 6B23</span> ile <span class='hl'>Radar, Frontier ve Supply Camp</span>'ta 30sn bekle." },
    { n: "Strage Things At The Farm", d: "• <span class='hl'>Farm Lockdown/Forbidden</span> modunda <span class='hl'>2 Boss</span> öldür." },
    { n: "Quick On Your Feet", d: "• <span class='hl'>ML Lever-Action Rifle</span> ile <span class='hl'>5 düşman</span> öldür." },
    { n: "Ghost Of The Past", d: "• Çeşitli haritalarda toplam <span class='hl'>11 adet Air Drop</span> konteyneri yağmala." },
    { n: "Edelweiss's Return", d: "• <span class='hl'>Valley Lockdown</span> modunda <span class='hl'>bacaklar kırıkken 8 düşman</span> öldür." },
    { n: "Team Annihilation", d: "• <span class='hl'>TV Station</span> haritasında <span class='hl'>7 medikal konteyner</span> yağmala.\n• <span class='hl'>Elevator</span> çıkışından çıkış yap." },
    { n: "Additional Troops", d: "• <span class='hl'>Armory</span> haritasında kutuya <span class='hl'>750k item</span> koy.\n• <span class='hl'>Underground Canal</span> çıkış yap." },
    { n: "Crow Feather", d: "• <span class='hl'>Northridge</span>'in 5 farklı bölgesinde <span class='hl'>birer adet kasa</span> yağmala." },
    { n: "Counterattack", d: "• <span class='hl'>TV Station</span> haritasında <span class='hl'>M84 Flashbang</span> ile <span class='hl'>6 kör etme</span> yap.\n• <span class='hl'>3 maç tamamla</span>." },
    { n: "By Name", d: "• <span class='hl'>TV Station</span>'daki <span class='hl'>3 farklı çıkış noktasını</span> en az birer kez kullan." },
    { n: "Predator", d: "• <span class='hl'>TV Station veya Airport</span> çıkış yap.\n• <span class='hl'>5 adet yağmalanmamış büyük kasa</span> yağmala." },
    { n: "Heavy Punch", d: "• <span class='hl'>Airport</span> haritasında <span class='hl'>8 adet Blackgold Scav</span> öldür." },
    { n: "Golden Opportunity", d: "• <span class='hl'>TV Station Central Control</span> puan topla.\n• <span class='hl'>The Vault</span> bölgesinde etkileşime gir." },
    { n: "Window Of Opportunity", d: "• <span class='hl'>Airport</span> haritasından <span class='hl'>15 adet altın/kırmızı eşya</span> çıkar." },
    { n: "Deja Vu", d: "• <span class='hl'>Farm</span> haritasında <span class='hl'>15 dakika hayatta kal</span>.\n• <span class='hl'>Cemetery</span> bölgesinde etkileşime gir." },
    { n: "The Final Showdown", d: "• <span class='hl'>Airport</span> haritasındaki <span class='hl'>4 stratejik odada</span> etkileşime geç." },
    { n: "Waving Flag", d: "• <span class='hl'>Airport Control Tower</span> bölgesinde <span class='hl'>10 düşman</span> öldür.\n• <span class='hl'>2 adet Encrypted Safe</span> yağmala." }
];